language: node_js
sudo: required
before_script:
  - npm install
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - xvfb-run npm test
dist: trusty
