language: node_js
sudo: required
before_script:
  - npm install -g bower polymer-cli
  - bower install
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - xvfb-run polymer test
dist: trusty
