name: test
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Calculate GZIPed Size
        uses: preactjs/compressed-size-action@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          build-script: analyze
          pattern: ./service-worker.js

