name: test
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Calculate GZIPed Size
        uses: preactjs/compressed-size-action@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          build-script: analyze
          pattern: ./service-worker.js

